In [160]:
import numpy as np

In [161]:
np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [162]:
a.shape

(4, 3)

In [163]:
a[1:,1:2]

array([[ 5],
       [ 8],
       [11]])

In [164]:
9 in a

True

In [165]:
p = np.array(range(10), int)

In [166]:
p

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
p = a.reshape(2,6)

In [113]:
p

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [98]:
d = np.array(range(27), int).reshape(3,9)

In [99]:
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [120]:
d.transpose()

array([[ 0,  9, 18],
       [ 1, 10, 19],
       [ 2, 11, 20],
       [ 3, 12, 21],
       [ 4, 13, 22],
       [ 5, 14, 23],
       [ 6, 15, 24],
       [ 7, 16, 25],
       [ 8, 17, 26]])

In [123]:
p.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [135]:
x = np.array(range(4), float).reshape(2,2)
y = np.array(range(4), int).reshape(2,2)

In [136]:
np.concatenate((x,y))

array([[0., 1.],
       [2., 3.],
       [0., 1.],
       [2., 3.]])

In [133]:
xy

array([[0., 1.],
       [2., 3.],
       [0., 1.],
       [2., 3.]])

In [137]:
np.arange(4)

array([0, 1, 2, 3])

In [138]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [142]:
np.ones_like([3,4,5])

array([1, 1, 1])

In [147]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [148]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [154]:
# Функция eye возвращает матрицу с единичками на к-атой диагонали
np.eye(5,4,-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [167]:
# Математические операции над массивами
# стандартные математические операции, должен соблюдаться принцип: элемент--элемент

In [174]:
a = np.array([1,2,3])
b = np.array([5,8,9])

a**2 * b - 50

array([-45, -18,  31])

In [175]:
# если размерность не совпадает (но кол-во внутри измерения равно) один массив 
# будет использован несколько раз

In [180]:
a = np.array(range(9)).reshape(3,3)
b = np.array([10, 100, 1000])

In [181]:
a + b

array([[  10,  101, 1002],
       [  13,  104, 1005],
       [  16,  107, 1008]])

In [182]:
# Вдобавок к стандартным операторам, в numpy включена библиотека стандартных 
# математических функций, которые могут быть применены поэлементно к массивам.
# Собственно функции: abs, sign, sqrt, log, log10, exp, sin, cos, tan, arcsin, 
# arccos, arctan, sinh, cosh, tanh, arcsinh, arccosh, и arctanh.

In [183]:
a = np.array([1,4,9,16])

In [188]:
np.sqrt(a)

array([1., 2., 3., 4.])

In [189]:
a = np.array([1.33, 1.55, 1.67])

In [193]:
np.floor(a)

array([1., 1., 1.])

In [194]:
np.ceil(a)

array([2., 2., 2.])

In [195]:
np.rint(a)

array([1., 2., 2.])

In [196]:
# Перебор элементов массива

In [223]:
a = np.array([[1,1,7,2,3], [26,-9,3,33,7]])

for (x,*z) in a:
    print(z)

[1, 7, 2, 3]
[-9, 3, 33, 7]


In [224]:
# Элементы могут быть суммированы или перемножены:

a.sum()

74

In [225]:
a.prod()

-6810804

In [226]:
a.mean() # среднее ариф.

7.4

In [227]:
# возвращаюют индекс макс и мин значений

In [228]:
a.argmin()

6

In [229]:
a.argmax()

8

In [230]:
sorted(a.flatten())

[-9, 1, 1, 2, 3, 3, 7, 7, 26, 33]

In [231]:
# можно подогнать элементы под нужный диапазон
a.flatten().clip(5,20)

array([ 5,  5,  7,  5,  5, 20,  5,  5, 20,  7])

In [232]:
np.unique(a)

array([-9,  1,  2,  3,  7, 26, 33])

In [236]:
# Получить диагональ массива
a = np.array(range(9)).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [237]:
a.diagonal()

array([0, 4, 8])

In [238]:
# Операторы сравнения и тестирование значений
x = np.array([1,2,2])
z = np.array([2,2,5])

In [246]:
x >= z

array([False,  True, False])

In [253]:
c = z <= 2
c

array([ True,  True, False])

In [254]:
# Операторы any и all могут быть использованы для определения 
# истинны ли хотя бы один или все элементы соответственно:

c.any()

True

In [255]:
c.all()

False

In [256]:
# Функция where создает новый массив из двух других массивов 
# одинаковых длин используя булев фильтр


In [262]:
a = np.array([1, 3, 1], float)
np.where(a != 0, 1 / a, a)

array([1.        , 0.33333333, 1.        ])

In [261]:
# С функцией where так же может быть реализовано «массовое сравнение»:
np.where(a > 0, 3, 2)

array([3, 3, 3])

In [264]:
# Выбор элементов массива и манипуляция с ними
a = np.array([[2,4], [5,3], [-3, 9]])

a[a > 3]

array([4, 5, 9])

In [265]:
gtzeto = (a > 0)
a[gtzeto]

array([2, 4, 5, 3, 9])

In [266]:
x = np.logical_and?

In [268]:
x = np.logical_and(a > 2, a < 5)
a[x]

array([4, 3])

In [270]:
# можно использовать целочисленные массивы
a = np.array([1,2,3], float)
b = np.array([0,0,2,2,1,1], int)
a[b]

array([1., 1., 3., 3., 2., 2.])

In [295]:
a = np.array([
    [2,4,5], 
    [5,3,8]
])
b = np.array([0,0,1])
c = np.array([0,0,0])
a[b,c]

array([2, 2, 5])

In [294]:
a = np.array([
    [2,4,5], 
    [5,3,8],
    [52,13,28]
])
b = np.array([0, 0, 1, 2, 0, 2])
c = np.array([2, 2, 2, 2, 2, 2])
a[c]

array([[52, 13, 28],
       [52, 13, 28],
       [52, 13, 28],
       [52, 13, 28],
       [52, 13, 28],
       [52, 13, 28]])

In [301]:
a = np.array([1,2,3], float)
a.take([0,0,2,0])

array([1., 1., 3., 1.])

In [308]:
a.put([0,2], [10,50, 100])
a

array([10.,  2., 50.])

In [ ]:
# Векторная и матричная математика

In [309]:
# Функция dot возвращает скалярное произведение векторов:
a = np.array([1, 2, 2])
b = np.array([1,4,5])
np.dot(a, b)

19

In [310]:
a = np.array([[0, 1], [2, 3]], float)
b = np.array([2, 3], float)
c = np.array([[1, 1], [4, 0]], float)
np.dot(b, a)

array([ 6., 11.])

In [311]:
np.dot(a,c)

array([[ 4.,  0.],
       [14.,  2.]])

In [313]:
# https://habr.com/ru/post/415373/  

# сложнааа на математике много чего, перечитай 

In [315]:
# Статистика
a = np.array([1, 4, 3, 8, 9, 2, 3], float)
np.median(a)

3.0

In [323]:
np.random.seed(12) # задать порождающий элемент 
np.random.rand(3) # сгенерировать кол-во случайных чисел

array([0.15416284, 0.7400497 , 0.26331502])

In [326]:
np.random.rand(3,5) # массив случайных чисел

array([[0.76813415, 0.16071675, 0.76456045, 0.0208098 , 0.13521018],
       [0.11627302, 0.30989758, 0.67145265, 0.47122978, 0.8161683 ],
       [0.28958678, 0.73312598, 0.70262236, 0.32756948, 0.33464753]])

In [347]:
np.random.randint(1000000000000000000, 3000000000000000001)

1256459660100794869